[toolchain]
channel = "nightly"
targets = [
        "aarch64-apple-darwin",         # macOS on ARM64
        "aarch64-unknown-linux-gnu",    # Linux on ARM64
        "aarch64-unknown-linux-musl",   # Linux on ARM64 with musl
        "aarch64-pc-windows-msvc",      # Windows on ARM64 with MSVC
        "x86_64-apple-darwin",          # macOS on x86_64
        "x86_64-unknown-linux-gnu",     # Linux on x86_64
        "x86_64-unknown-linux-musl",    # Linux on x86_64 with musl
        "x86_64-pc-windows-msvc",       # Windows on x86_64 with MSVC
        "x86_64-pc-windows-gnu",        # Windows on x86_64 with GNU
]
[target.'cfg(target_os = "macos")']
profile = "minimal"
[target.'cfg(target_os = "linux")']
profile = "minimal"
[target.x86_64-pc-windows-gnu]
profile = "minimal"