name: Rust Windows-Linux-Darwin Cross Build

on:
  release:
    types:
      - created  # Trigger this workflow when a release is created
  workflow_dispatch:  # Manual trigger

jobs:
  # Docker-based Linux-Darwin build on Ubuntu
  build-linux-darwin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get the latest tag if no tag is provided by the release
      - name: Get latest tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker Image
        run: |
          mkdir -p /tmp/.docker-cache
          docker pull joseluisq/rust-linux-darwin-builder:latest
          docker save joseluisq/rust-linux-darwin-builder:latest -o /tmp/.docker-cache/rust-linux-darwin-builder.tar

      - name: Make shell script executable
        run: chmod +x ./build.sh

      - name: Run Shell Script
        run: ./build.sh

      # Archive build artifacts (bin folder)
      - name: Archive build artifacts
        run: |
          mkdir -p artifacts
          cp -r ./bin/* artifacts/

      # Upload Linux-Darwin artifacts to release
      - name: Upload Linux-Darwin artifacts to release
        run: |
          TAG=${{ github.event.release.tag_name }}
          for file in ./artifacts/*; do
            echo "Uploading $file"
            gh release upload $TAG $file --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Windows build for both GNU and MSVC targets using cargo
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get the latest tag if no tag is provided by the release
      - name: Get latest tag
        id: get-latest-tag
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      # Install Visual Studio Build Tools using Chocolatey
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive"

      - name: Set up Rust toolchain for Windows
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add MSVC target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Add GNU target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build project for Windows GNU
        run: cargo build --release --all-features --target x86_64-pc-windows-gnu

      - name: Build project for Windows MSVC
        run: cargo build --release --all-features --target x86_64-pc-windows-msvc

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Copy Windows builds to artifacts
        run: |
          copy target\x86_64-pc-windows-gnu\release\*.exe artifacts\
          copy target\x86_64-pc-windows-msvc\release\*.exe artifacts\

      # Upload Windows artifacts to release
      - name: Upload Windows artifacts to release
        run: |
          $TAG=${{ github.event.release.tag_name }}
          $artifacts = Get-ChildItem -Path ./artifacts
          foreach ($file in $artifacts) {
            Write-Host "Uploading $file"
            gh release upload $TAG $file.FullName --clobber
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

