name: Makefile CI

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Docker on the runner
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.6.1

    # Pull and update Docker image
    - name: Update Docker Image
      run: |
        docker pull joseluisq/rust-linux-darwin-builder:latest

    # Execute Makefile to compile targets
    - name: Compile project with Makefile
      run: |
        make compile

    # Debugging: List compiled files to check they exist
    - name: List compiled files
      run: ls -la target

    # Upload files to GitHub Release using svenstaro/upload-release-action
    - name: Upload to GitHub Release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: |
          target/x86_64-apple-darwin/release/crypted-messages-x86_64-apple-darwin
          target/aarch64-apple-darwin/release/crypted-messages-aarch64-apple-darwin
          target/x86_64-unknown-linux-gnu/release/crypted-messages-x86_64-unknown-linux-gnu
          target/x86_64-unknown-linux-musl/release/crypted-messages-x86_64-unknown-linux-musl
          target/aarch64-unknown-linux-gnu/release/crypted-messages-aarch64-unknown-linux-gnu
          target/aarch64-unknown-linux-musl/release/crypted-messages-aarch64-unknown-linux-musl
        tag: ${{ github.ref }}
        overwrite: true
